# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.boot_timeout = 1200

  nodes = [
    { :hostname => "k8s-master", :ip => "192.168.56.10", :provision => "init-master.sh" },
    { :hostname => "k8s-worker1", :ip => "192.168.56.11", :provision => "join-workers.sh" },
    { :hostname => "k8s-worker2", :ip => "192.168.56.12", :provision => "join-workers.sh" }
  ]

  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.hostname = node[:hostname]
      nodeconfig.vm.network "private_network", ip: node[:ip]

      nodeconfig.vm.provider "virtualbox" do |vb|
        if node[:hostname] == "k8s-master"
          vb.memory = 4096
          vb.cpus = 4
        else
          vb.memory = 3072
          vb.cpus = 2
        end

        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      end
      
      # Fix DNS resolution
      nodeconfig.vm.provision "shell", inline: <<-SHELL
        echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
        echo "nameserver 8.8.4.4" | sudo tee -a /etc/resolv.conf > /dev/null
      SHELL
      
      nodeconfig.vm.provision "shell", path: "provision.sh"
      nodeconfig.vm.provision "shell", path: node[:provision]
    end
  end
end
