apiVersion: apps/v1
kind: Deployment
metadata:
  name: gv-frontend
  namespace: gv-webstack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gv-frontend
  template:
    metadata:
      labels:
        app: gv-frontend
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - gv-frontend
                topologyKey: kubernetes.io/hostname
      containers:
        - name: gv-frontend
          image: frontend-apache
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
