apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gv-postgres-pvc-v2
  namespace: gv-webstack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
